fix: add missing status UnexpectedlyUnpinned (#1105)
Pins cron is currently failing with:

```
Error: unknown tracker status: unexpectedly_unpinned
    at toPinStatusEnum (file:///home/runner/work/web3.storage/web3.storage/packages/api/src/utils/pin.js:52:11)
    at file:///home/runner/work/web3.storage/web3.storage/packages/cron/src/jobs/pins.js:67:20
    at Array.map (<anonymous>)
    at updatePinStatuses (file:///home/runner/work/web3.storage/web3.storage/packages/cron/src/jobs/pins.js:52:49)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async main (file:///home/runner/work/web3.storage/web3.storage/packages/cron/src/bin/pins.js:16:3)
```

https://github.com/web3-storage/web3.storage/runs/5509298651?check_suite_focus=true

...this is because we do not model this new status in our API code or in our DB schema yet.

resolves https://github.com/web3-storage/web3.storage/issues/912